# Generated by Django 5.1.3 on 2024-11-17 02:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import reg.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_form', models.DateField(default='2024-01-01')),
                ('situacao_cliente', models.CharField(default='Cadastro', max_length=50)),
                ('cod_cliente', models.CharField(default='0000', max_length=10)),
                ('emp_cnpj', models.CharField(default='00.000.000/0000-00', max_length=18)),
                ('emp_cpf', models.CharField(default='000.000.000-00', max_length=14)),
                ('emp_ie', models.CharField(default='000.000', max_length=9)),
                ('tipo_cliente', models.CharField(default='', max_length=50)),
                ('razao_nome', models.CharField(default='', max_length=255)),
                ('fantasia_nome', models.CharField(default='', max_length=255)),
                ('cep', models.CharField(default='00000-000', max_length=9)),
                ('rua', models.CharField(default='Rua exemplo', max_length=255)),
                ('bairro', models.CharField(default='Bairro exemplo', max_length=255)),
                ('cidade', models.CharField(default='Cidade exemplo', max_length=255)),
                ('estado', models.CharField(default='XX', max_length=2)),
                ('complemento', models.CharField(default='', max_length=255, null=True)),
                ('produto_desc', models.CharField(default='Produto padrão', max_length=255)),
                ('valor_desc', models.CharField(max_length=255, null=True)),
                ('prazo_desc', models.CharField(max_length=255, null=True)),
                ('comp_emp', models.CharField(max_length=255, null=True)),
                ('num_endr', models.CharField(max_length=10, null=True)),
                ('email_empresa', models.CharField(max_length=255, null=True)),
                ('telefone_empresa', models.CharField(max_length=255, null=True)),
                ('referencia1', models.CharField(default='Referência 1', max_length=255)),
                ('contato1', models.CharField(default='(00) 0000-0000', max_length=20)),
                ('referencia2', models.CharField(default='Referência 2', max_length=255)),
                ('contato2', models.CharField(default='(00) 0000-0000', max_length=20)),
                ('referencia3', models.CharField(default='Referência 3', max_length=255)),
                ('contato3', models.CharField(default='(00) 0000-0000', max_length=20)),
                ('referencia4', models.CharField(default='Referência 4', max_length=255)),
                ('contato4', models.CharField(default='(00) 0000-0000', max_length=20)),
                ('referencia5', models.CharField(default='Referência 5', max_length=255)),
                ('contato5', models.CharField(default='(00) 0000-0000', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivos_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('arquivo', models.FileField(null=True, upload_to=reg.models.local_arq)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_empresas', to='reg.empresa')),
            ],
        ),
    ]
