# Generated by Django 5.1.3 on 2024-11-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargos',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rca',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
